name: Presence
version: ${project.version}

authors: [Geolykt]

main: de.geolykt.presence.PresenceBukkit
api-version: '1.18'
softdepend: [PlaceholderAPI]

commands:
  claims:
    description: Claims and you; /claims help.
    usage: /claims
    default: true
  claimFly:
    aliases: [cfly]
    default: true
  chunkgroups:
    aliases: [cgroup, chunkgroup, groups, claimgroup, claimgroups]
    description: Manage chunk groups
