name: Presence
version: ${project.version}

authors: [Geolykt]

main: de.geolykt.presence.PresenceBukkit
api-version: '1.18'
softdepend: [PlaceholderAPI]

commands:
  claims:
    description: Claims and you; /claims help.
    usage: /claims
    default: true
  claimFly:
    aliases: [cfly]
    default: true
  forceclaim:
    description: OP-only command to claim stuff
    usage: /forceclaim [amount]
    default: op
